# Generated by Django 5.2.9 on 2025-12-14 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryThrottle',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_send_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_seconds', models.PositiveIntegerField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_handle', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACCEPTED', 'Accepted'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('RECEIVED', 'Received'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='QUEUED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_for', 'created_at'], name='scheduler_s_status_078341_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageStatusEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACCEPTED', 'Accepted'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('RECEIVED', 'Received'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduler.scheduledmessage')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
