# Generated by Django 5.2.9 on 2025-12-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverythrottle',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='deliverythrottle',
            name='retry_base_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='deliverythrottle',
            name='retry_max_seconds',
            field=models.PositiveIntegerField(default=21600),
        ),
    ]
